# src/langgraph_system/config/nodes_config.yaml

student_profile_node:
  name: Student Profile Node
  description: Manages student profiles by interacting with the database.

monitor_node:
  name: Monitor Node
  description: Monitors student activity and reports progress.

decision_engine_node:
  name: Decision Engine Node
  description: Determines if adjustments are needed in the student's learning path.

teacher_profile_node:
  name: Teacher Profile Node
  description: Provides teaching prompts to the Monitor Node.

educational_crewai_node:
  name: Educational CrewAI Node
  description: Represents the CrewAI subsystem, generating tailored content.
